// ----------------------------------------------------------------------

export const fullName = [
  'Jayvion Simon',
  'Lucian Obrien',
  'Deja Brady',
  'Harrison Stein',
  'Reece Chung',
  'Lainey Davidson',
  'Cristopher Cardenas',
  'Melanie Noble',
  'Chase Day',
  'Shawn Manning',
  'Soren Durham',
  'Cortez Herring',
  'Brycen Jimenez',
  'Giana Brandt',
  'Aspen Schmitt',
  'Colten Aguilar',
  'Angelique Morse',
  'Selina Boyer',
  'Lawson Bass',
  'Ariana Lang',
  'Amiah Pruitt',
  'Harold Mcgrath',
  'Esperanza Mcintyre',
  'Mireya Conner',
  'Jamie Kline',
  'Laney Vazquez',
  'Tiffany May',
  'Dexter Shepherd',
  'Jaqueline Spencer',
  'Londyn Jarvis',
  'Yesenia Butler',
  'Jayvon Hull',
  'Izayah Pope',
  'Ayana Hunter',
  'Isabell Bender',
  'Desiree Schmidt',
  'Aidan Stout',
  'Jace Bush',
  'Janiya Williamson',
  'Hudson Alvarez'
];

export const firstName = [
  'Ahmed',
  'Anis',
  'Haythem',
  'Farouk',
  'Mohammed',
  'Firas',
  'Fares',
  'Oussema',
  'Ameur',
  'Saber',
  'Wassim',
  'Sami',
  'Hichem',
  'Siwar',
  'Meriem',
  'Tayssir',
  'Molka',
  'Hanen',
  'Hanin',
  'Oumaima',
  'Balkis'
];

export const lastName = [
  'Khadhraoui',
  'Achouri',
  'Khalfi',
  'Ghannouchi',
  'Said',
  'Chaabeni',
  'lahmer',
  'Hosni',
  'bokri',
  'Bekri',
  'Ben nasr',
  'Chouaieb',
  'lassoued',
  'Lakhel',
  'ben Yaghlen',
  'Abid',
  'Ben Ali',
  'Abdelli',
  'Abidi',
  'Yahya',
  'Ben hammouda'
];
